name: GitHub Environments Configuration

environments:
  dev:
    deployment_branch_policy:
      protected_branches: false
      custom_branches:
        - master
    
  qa:
    deployment_branch_policy:
      protected_branches: true
      custom_branches:
        - main
    reviewers:
      - DebonairSM  