version: '3.8'

services:
  api:
    build:
      context: ./EnterpriseApiIntegration.Api
      dockerfile: Dockerfile
      args:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: https://+:443;http://+:80
        ASPNETCORE_Kestrel__Certificates__Default__Password: YourSecurePassword
        ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
        UseDevAuthentication: false
        ConnectionStrings__DefaultConnection: Server=db;Database=AviationDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
        MicrosoftEntraId__Instance: https://login.microsoftonline.com/
        MicrosoftEntraId__Domain: rommelbgmail.onmicrosoft.com
        MicrosoftEntraId__TenantId: 621db766-1ccd-40f1-80b0-ef469bd8f081
        MicrosoftEntraId__ClientId: 9955b442-bb6b-4224-85de-d0476bf8a0f6
        MicrosoftEntraId__CallbackPath: /signin-oidc
        MicrosoftEntraId__SignedOutCallbackPath: /signout-callback-oidc
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourSecurePassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - UseDevAuthentication=false
      - ConnectionStrings__DefaultConnection=Server=db;Database=AviationDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - MicrosoftEntraId__Instance=https://login.microsoftonline.com/
      - MicrosoftEntraId__Domain=rommelbgmail.onmicrosoft.com
      - MicrosoftEntraId__TenantId=621db766-1ccd-40f1-80b0-ef469bd8f081
      - MicrosoftEntraId__ClientId=9955b442-bb6b-4224-85de-d0476bf8a0f6
      - MicrosoftEntraId__CallbackPath=/signin-oidc
      - MicrosoftEntraId__SignedOutCallbackPath=/signout-callback-oidc
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqldata: 