name: Deploy to Azure QA

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag to deploy (e.g., v1.0.0)'
        required: true
      confirm_deployment:
        description: 'Type "yes" to confirm deployment to QA'
        required: true

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'EnterpriseApiIntegration.sln'
  RESOURCE_GROUP: 'rg-aviation-qa'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Validate confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_deployment }}" != "yes" ]; then
          echo "Deployment not confirmed. Please type 'yes' to confirm deployment to QA."
          exit 1
        fi

  build-and-deploy:
    needs: validate
    runs-on: ubuntu-latest
    environment: qa
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.version_tag }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

    - name: Publish
      run: |
        dotnet publish AzureMicroservicesPlatform.Identity/AzureMicroservicesPlatform.Identity.csproj -c Release -o ./publish/identity
        dotnet publish AzureMicroservicesPlatform.Services.Aircraft/AzureMicroservicesPlatform.Services.Aircraft.csproj -c Release -o ./publish/aircraft
        dotnet publish AzureMicroservicesPlatform.Services.Customers/AzureMicroservicesPlatform.Services.Customers.csproj -c Release -o ./publish/customers
        dotnet publish AzureMicroservicesPlatform.Services.Subscriptions/AzureMicroservicesPlatform.Services.Subscriptions.csproj -c Release -o ./publish/subscriptions

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy to Azure Web Apps
    - name: Deploy Identity Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aviation-identity-qa'
        package: './publish/identity'
        app-settings: |
          WEBSITE_RUN_FROM_PACKAGE=1
          ASPNETCORE_ENVIRONMENT=QA
          ConnectionStrings__DefaultConnection=${{ secrets.IDENTITY_DB_CONNECTION }}

    - name: Deploy Aircraft Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aviation-aircraft-qa'
        package: './publish/aircraft'
        app-settings: |
          WEBSITE_RUN_FROM_PACKAGE=1
          ASPNETCORE_ENVIRONMENT=QA
          ConnectionStrings__DefaultConnection=${{ secrets.AIRCRAFT_DB_CONNECTION }}

    - name: Deploy Customers Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aviation-customers-qa'
        package: './publish/customers'
        app-settings: |
          WEBSITE_RUN_FROM_PACKAGE=1
          ASPNETCORE_ENVIRONMENT=QA
          ConnectionStrings__DefaultConnection=${{ secrets.CUSTOMERS_DB_CONNECTION }}

    - name: Deploy Subscriptions Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aviation-subscriptions-qa'
        package: './publish/subscriptions'
        app-settings: |
          WEBSITE_RUN_FROM_PACKAGE=1
          ASPNETCORE_ENVIRONMENT=QA
          ConnectionStrings__DefaultConnection=${{ secrets.SUBSCRIPTIONS_DB_CONNECTION }}

    - name: Azure Logout
      run: az logout
      if: always() 