name: Deploy to Azure Production

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag to deploy (e.g., v1.0.0)'
        required: true
      confirm_deployment:
        description: 'Type "yes" to confirm deployment to Production'
        required: true
      deployment_approval:
        description: 'Deployment approval ticket number'
        required: true

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'EnterpriseApiIntegration.sln'
  REGISTRY_NAME: 'aviationqa2024'
  RESOURCE_GROUP: 'rg-aviation-prod'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Validate confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_deployment }}" != "yes" ]; then
          echo "Deployment not confirmed. Please type 'yes' to confirm deployment to Production."
          exit 1
        fi
        if [ -z "${{ github.event.inputs.deployment_approval }}" ]; then
          echo "Deployment approval ticket number is required for production deployment."
          exit 1
        fi

  deploy-to-prod:
    needs: validate
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.version_tag }}
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Deploy to Azure Web Apps (using existing images from Pre-Prod)
    - name: Deploy Identity Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aviation-identity-prod'
        images: '${{ env.REGISTRY_NAME }}.azurecr.io/identity:${{ github.event.inputs.version_tag }}'

    - name: Deploy Aircraft Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aviation-aircraft-prod'
        images: '${{ env.REGISTRY_NAME }}.azurecr.io/aircraft:${{ github.event.inputs.version_tag }}'

    - name: Deploy Customers Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aviation-customers-prod'
        images: '${{ env.REGISTRY_NAME }}.azurecr.io/customers:${{ github.event.inputs.version_tag }}'

    - name: Deploy Subscriptions Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aviation-subscriptions-prod'
        images: '${{ env.REGISTRY_NAME }}.azurecr.io/subscriptions:${{ github.event.inputs.version_tag }}'

    - name: Azure Logout
      run: az logout
      if: always() 