name: Environment Setup

on:
  workflow_dispatch:

jobs:
  setup-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Dev environment check
        run: echo "Dev environment is ready"

  setup-qa:
    runs-on: ubuntu-latest
    environment: qa
    needs: setup-dev
    steps:
      - name: QA environment check
        run: echo "QA environment is ready" 