name: Terraform Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (qa)'
        required: true
        default: 'qa'
      confirm:
        description: 'Type "yes" to confirm deployment'
        required: true

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_WORKSPACE: qa

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Validate environment
      run: |
        if [ "${{ github.event.inputs.environment }}" != "qa" ]; then
          echo "Invalid environment. Only 'qa' is supported."
          exit 1
        fi
        if [ "${{ github.event.inputs.confirm }}" != "yes" ]; then
          echo "Deployment not confirmed. Please type 'yes' to confirm."
          exit 1
        fi

  terraform:
    needs: validate
    runs-on: ubuntu-latest
    environment: qa
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "~1.7.0"

    - name: Terraform Init
      run: |
        cd terraform/environments/qa
        terraform init \
        -backend-config="resource_group_name=rg-terraform-state" \
        -backend-config="storage_account_name=tfstate2024aviation" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=terraform.tfstate"

    - name: Terraform Plan
      run: |
        cd terraform/environments/qa
        terraform plan -out=tfplan

    - name: Terraform Apply
      if: github.event.inputs.confirm == 'yes'
      run: |
        cd terraform/environments/qa
        terraform apply -auto-approve tfplan 